// Generates the film's sound on ElevenLabs (free tier): voiceover with word timings,
// the sound-design palette, and music-bed candidates. Reads ELEVENLABS_API_KEY from .env.
//
//   node scripts/audio_gen.mjs vo       -> assets/audio/vo/*.mp3 + assets/audio/words.js
//   node scripts/audio_gen.mjs vo vo6   -> only vo6 (the other lines' audio and timings are kept)
//   node scripts/audio_gen.mjs sfx      -> assets/sfx/*.mp3        (skips files that exist)
//   node scripts/audio_gen.mjs music    -> assets/audio/bed-*.mp3
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const env = Object.fromEntries(fs.readFileSync(path.join(ROOT, '.env'), 'utf8').split(/\r?\n/).filter((l) => l.includes('='))
  .map((l) => [l.slice(0, l.indexOf('=')).trim(), l.slice(l.indexOf('=') + 1).trim()]));
const H = { 'xi-api-key': env.ELEVENLABS_API_KEY, 'Content-Type': 'application/json' };
const API = 'https://api.elevenlabs.io';
const ctx = { globalThis: {} };
vm.runInNewContext(fs.readFileSync(path.join(ROOT, 'timing.js'), 'utf8'), ctx);
const T = ctx.globalThis.HERCOVA_TIMING;

// Matilda — "Knowledgable, Professional", upbeat American (ElevenLabs premade, free plan), on the v3 model.
// Chosen by ear from renders/voice-samples (2026-09-29); the previous voice was Lily (pFZP5JQG7iQjIQuC4Bku).
const VOICE = 'XrExE9yKIg1WjnnlVkGX';
const MODEL = 'eleven_v3';

function toWords(al) {
  const words = [];
  let cur = null;
  for (let i = 0; i < al.characters.length; i++) {
    const ch = al.characters[i];
    if (/\s/.test(ch)) { if (cur) { words.push(cur); cur = null; } continue; }
    if (!cur) cur = [ '', +al.character_start_times_seconds[i].toFixed(3), 0 ];
    cur[0] += ch;
    cur[2] = +al.character_end_times_seconds[i].toFixed(3);
  }
  if (cur) words.push(cur);
  return words;
}

async function vo(only = []) {
  const out = path.join(ROOT, 'assets/audio/vo');
  fs.mkdirSync(out, { recursive: true });
  // regenerate only the named lines (e.g. `vo vo6`), keeping every other line's audio and timings
  const words = {};
  const prev = path.join(ROOT, 'assets/audio/words.js');
  if (only.length && fs.existsSync(prev)) {
    const c = { globalThis: {} };
    vm.runInNewContext(fs.readFileSync(prev, 'utf8'), c);
    Object.assign(words, c.globalThis.HERCOVA_WORDS);
  }
  for (const line of T.vo) {
    if (only.length && !only.includes(line.id)) continue;
    const r = await fetch(`${API}/v1/text-to-speech/${VOICE}/with-timestamps?output_format=mp3_44100_128`, {
      method: 'POST', headers: H,
      body: JSON.stringify({ text: line.text, model_id: MODEL, voice_settings: { stability: 0.5, similarity_boost: 0.8, style: 0.3, use_speaker_boost: true } }),
    });
    const j = await r.json();
    if (!r.ok) throw new Error(`${line.id}: ${r.status} ${JSON.stringify(j).slice(0, 200)}`);
    fs.writeFileSync(path.join(out, `${line.id}.mp3`), Buffer.from(j.audio_base64, 'base64'));
    words[line.id] = toWords(j.alignment);
    const w = words[line.id];
    console.log(line.id, `${w.length} words, speech ${w[0][1]}-${w.at(-1)[2]}s`);
  }
  fs.writeFileSync(path.join(ROOT, 'assets/audio/words.js'),
    `// Generated by scripts/audio_gen.mjs — ElevenLabs word alignment per VO line: [text, start, end] seconds from the line's start.\n` +
    `(function (g) { g.HERCOVA_WORDS = ${JSON.stringify(words)}; })(typeof window !== 'undefined' ? window : globalThis);\n`);
}

// One sound per motion hit. Durations in seconds.
const SFX = [
  ['heartbeat', 4.0, 'soft warm human heartbeat, slow and gentle, intimate cinematic low thumps, clean, no hiss'],
  ['ignite', 1.8, 'soft magical glow igniting, warm shimmer bloom with gentle sub swell, elegant'],
  ['ripple', 1.6, 'soft sonar ripple ping, airy and warm, gentle, not alarming'],
  ['iris', 1.8, 'cinematic reveal swoosh, airy whoosh opening like a portal with soft shimmer'],
  ['typehit', 1.6, 'deep soft cinematic impact for a title, warm, elegant, subtle boom with short tail'],
  ['tickrun', 2.2, 'clock ticking very fast, soft ticks accelerating then stopping abruptly, clean'],
  ['dissolve', 2.8, 'glittering particles dissolving and swirling, granular magical sand whoosh, sparkling'],
  ['lowhit', 2.6, 'soft deep sub drop, gentle single low boom with a long soft tail, emotional'],
  ['dive', 1.5, 'fast cinematic zoom whoosh diving forward, rushing air building to a cut'],
  ['zip', 1.6, 'glowing energy line zipping through the air and circling, smooth magical swoosh'],
  ['whip', 0.7, 'quick smooth camera whip pan whoosh, airy'],
  ['pop', 0.5, 'soft rounded bubble pop, gentle UI'],
  ['pages', 1.1, 'soft paper book pages flipping quickly, gentle'],
  ['alert', 2.2, 'gentle warm notification chime, two soft bell tones rising, reassuring and kind'],
  ['swell', 3.2, 'warm cinematic riser swelling to a soft bright resolve, hopeful, airy, no drums'],
  ['bloom', 2.6, 'soft warm airy whoosh of light, heavenly shimmer, emotional reveal'],
  ['logo', 2.6, 'premium logo reveal, warm deep soft impact with an airy sparkle tail'],
  ['click', 0.5, 'soft satisfying premium button click'],
  ['shimmer', 1.3, 'tiny delicate glass shimmer sparkle, a light sweep across glass'],
  ['nodes', 1.3, 'four soft glassy plinks in quick rising succession, gentle UI'],
];

async function sfx() {
  const out = path.join(ROOT, 'assets/sfx');
  fs.mkdirSync(out, { recursive: true });
  for (const [id, dur, prompt] of SFX) {
    const f = path.join(out, `${id}.mp3`);
    if (fs.existsSync(f)) { console.log(id, 'exists'); continue; }
    const r = await fetch(`${API}/v1/sound-generation?output_format=mp3_44100_128`, {
      method: 'POST', headers: H, body: JSON.stringify({ text: prompt, duration_seconds: dur, prompt_influence: 0.6 }),
    });
    if (!r.ok) { console.log(id, 'FAILED', r.status, (await r.text()).slice(0, 160)); continue; }
    fs.writeFileSync(f, Buffer.from(await r.arrayBuffer()));
    console.log(id, 'ok');
  }
}

async function music() {
  const beds = [
    ['bed-a', 'Warm hopeful cinematic film score underscore: soft felt piano melody over a warm string pad, a gentle low heartbeat pulse, slowly building to an emotional uplifting resolve. No vocals. High quality, polished.'],
    ['bed-b', 'Uplifting inspiring ambient brand film music: airy synth pads, delicate plucked arpeggio, soft piano, warm cinematic swells building to a hopeful major resolve. No drums, no vocals. Polished and premium.'],
  ];
  for (const [id, prompt] of beds) {
    for (const dur of [30, 22]) {
      const r = await fetch(`${API}/v1/sound-generation?output_format=mp3_44100_128`, {
        method: 'POST', headers: H, body: JSON.stringify({ text: prompt, duration_seconds: dur, prompt_influence: 0.45 }),
      });
      if (!r.ok) { console.log(id, dur, 'FAILED', r.status, (await r.text()).slice(0, 160)); continue; }
      fs.writeFileSync(path.join(ROOT, `assets/audio/${id}.mp3`), Buffer.from(await r.arrayBuffer()));
      console.log(id, dur, 'ok');
      break;
    }
  }
}

const [cmd, ...rest] = process.argv.slice(2);
await ({ vo, sfx, music }[cmd] ?? (() => console.log('usage: vo [ids...] | sfx | music')))(rest);
