"""Bakes the payoff's halftone (mother + baby) into assets/data/mb_particles.js.

Samples the graded, cut-out photograph exactly where it sits on screen in the payoff
(MB placement must match film.js), keeping only her silhouette. film.js streams the
dots out of her orange dot into this halftone, resolves it into the photograph, and
later collapses it back into the dot.

    .venv/Scripts/python scripts/bake_mb.py
"""
import json, os
import numpy as np
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MB = dict(x=540, y=-40, s=0.6039)  # mb-color.png (1472x1954) on screen: 889x1180, top-left (540, -40) — must match #mbImg
im = np.asarray(Image.open(os.path.join(ROOT, "assets", "images", "graded", "mb-color.png")).convert("RGBA")).astype(np.float32)
H, W, _ = im.shape
rng = np.random.default_rng(5)
STEP = 17.0
pts = []
for sy in np.arange(MB["y"] + STEP / 2, min(1080, MB["y"] + H * MB["s"]), STEP):
    for sx in np.arange(MB["x"] + STEP / 2, MB["x"] + W * MB["s"], STEP):
        x, y = sx + rng.uniform(-2.5, 2.5), sy + rng.uniform(-2.5, 2.5)
        px, py = int(np.clip((x - MB["x"]) / MB["s"], 0, W - 1)), int(np.clip((y - MB["y"]) / MB["s"], 0, H - 1))
        if im[py, px, 3] < 128:
            continue
        patch = im[max(0, py - 7):py + 7, max(0, px - 7):px + 7, :3].reshape(-1, 3).mean(axis=0)
        lum = float(patch @ np.array([0.2126, 0.7152, 0.0722]) / 255.0)
        pts.append([round(x, 1), round(y, 1), round(1.4 + 6.4 * (1 - lum) ** 1.1, 2), "#%02x%02x%02x" % tuple(int(c) for c in patch)])
with open(os.path.join(ROOT, "assets", "data", "mb_particles.js"), "w", encoding="utf8") as f:
    f.write("// Generated by scripts/bake_mb.py — do not edit by hand.\n(function (g) { g.HERCOVA_MB = " + json.dumps({"pts": pts, "place": MB}) + "; })(typeof window !== 'undefined' ? window : globalThis);\n")
print("mb particles", len(pts))
