"""Bakes the photo -> particles hand-off (scene 3) into assets/data/particles.js.

Samples the graded hero photo, exactly where it sits on screen in scene 2, on a jittered
grid inside the photo window. Each sample becomes one particle: its screen position, a
halftone radius from its darkness, and its colour. film.js pairs each particle with a
dot of the Nigeria map and flies it there, so the photograph visibly becomes the map.

Layout constants must match film.js (PHOTO + WIN).

    .venv/Scripts/python scripts/bake_particles.py
"""
import json
import os

import numpy as np
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IMG = os.path.join(ROOT, "assets", "images", "graded")

PHOTO = dict(x=1040, y=60, s=0.5)          # hero-mono.jpg (1600x2000) placed at 800x1000 on screen
WIN = dict(x0=1110, y0=150, x1=1840, y1=1060)  # region her silhouette occupies in scene 2

img = np.asarray(Image.open(os.path.join(IMG, "hero-mono.jpg")).convert("RGB")).astype(np.float32)
H, W, _ = img.shape
alpha = None
cut = os.path.join(IMG, "hero-cutout.png")
if os.path.exists(cut):
    alpha = np.asarray(Image.open(cut).convert("RGBA").resize((W, H), Image.LANCZOS))[..., 3].astype(np.float32) / 255.0

rng = np.random.default_rng(11)
STEP = 15.5
pts = []
ys = np.arange(WIN["y0"] + STEP / 2, WIN["y1"], STEP)
xs = np.arange(WIN["x0"] + STEP / 2, WIN["x1"], STEP)
for sy in ys:
    for sx in xs:
        jx, jy = rng.uniform(-3, 3, 2)
        x, y = sx + jx, sy + jy
        px = int(np.clip((x - PHOTO["x"]) / PHOTO["s"], 0, W - 1))
        py = int(np.clip((y - PHOTO["y"]) / PHOTO["s"], 0, H - 1))
        # average a small patch so each particle carries the tone of its cell
        patch = img[max(0, py - 10):py + 10, max(0, px - 10):px + 10].reshape(-1, 3).mean(axis=0)
        lum = float(patch @ np.array([0.2126, 0.7152, 0.0722]) / 255.0)
        subj = float(alpha[py, px]) if alpha is not None else float(lum < 0.8)
        if subj < 0.5:
            continue  # only her: the particles carry her silhouette, not a rectangle
        r = 1.6 + 6.2 * (1.0 - lum) ** 1.1
        col = "#%02x%02x%02x" % tuple(int(c) for c in patch)
        pts.append([round(x, 1), round(y, 1), round(r, 2), col, round(subj, 2)])

# her: the particle nearest her heart, where the opening put her dot (image (760, 980), as in bake_silhouette.py)
hx, hy = PHOTO["x"] + 760 * PHOTO["s"], PHOTO["y"] + 980 * PHOTO["s"]
her = int(np.argmin([(p[0] - hx) ** 2 + (p[1] - hy) ** 2 for p in pts]))

out = "// Generated by scripts/bake_particles.py — do not edit by hand.\n" \
      "(function (g) { g.HERCOVA_PARTICLES = " + json.dumps({"pts": pts, "her": her, "step": STEP, "cutout": alpha is not None}) + \
      "; })(typeof window !== 'undefined' ? window : globalThis);\n"
with open(os.path.join(ROOT, "assets", "data", "particles.js"), "w", encoding="utf8") as f:
    f.write(out)
print(f"particles {len(pts)}, her #{her}, cutout {'yes' if alpha is not None else 'no'}")
