"""Bakes her silhouette (the hero cut-out's outline) for the opening into assets/data/silhouette.js.

The opening's heartbeat line runs in from the left edge, meets her at the front of her
silhouette (E), splits, and two pens draw her outline up over the gele and down past her
bump until both reach the bottom of the frame. Screen placement must match #photoSubject
(1600x2000 shown at 800x1000, top-left 1040,60).

    .venv/Scripts/python scripts/bake_silhouette.py
"""
import json
import os

import cv2
import numpy as np
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PHOTO = dict(x=1040, y=60, s=0.5)
HEART_IMG = (760, 980)  # her chest, just under the necklace, in image pixels
STEP = 3.0              # screen px between path samples

a = np.asarray(Image.open(os.path.join(ROOT, "assets", "images", "graded", "hero-cutout.png")).convert("RGBA"))[..., 3]
m = (a > 110).astype(np.uint8) * 255
m = cv2.morphologyEx(m, cv2.MORPH_CLOSE, cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (15, 15)))
m = cv2.morphologyEx(m, cv2.MORPH_OPEN, cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (9, 9)))
cs, _ = cv2.findContours(m, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
c = max(cs, key=cv2.contourArea)[:, 0, :].astype(np.float64)
H = a.shape[0]

# open the outline where it runs along the bottom edge of the photograph
on_bottom = c[:, 1] >= H - 4
if on_bottom.any():
    idx = np.nonzero(on_bottom)[0]
    # rotate so the path starts just after the bottom run and ends just before it
    runs = np.split(idx, np.nonzero(np.diff(idx) > 1)[0] + 1)
    last = max(runs, key=len)
    start = (last[-1] + 1) % len(c)
    c = np.roll(c, -start, axis=0)
    keep = c[:, 1] < H - 4
    first_bad = np.argmax(~keep) if (~keep).any() else len(c)
    c = c[:first_bad]

# smooth (circular moving average would wrap; this is an open path) and move to screen space
k = 9
pad = np.pad(c, ((k, k), (0, 0)), mode="edge")
ker = np.ones(2 * k + 1) / (2 * k + 1)
c = np.stack([np.convolve(pad[:, 0], ker, mode="valid"), np.convolve(pad[:, 1], ker, mode="valid")], axis=1)
scr = np.stack([PHOTO["x"] + c[:, 0] * PHOTO["s"], PHOTO["y"] + c[:, 1] * PHOTO["s"]], axis=1)

# resample at even spacing
seglen = np.hypot(*np.diff(scr, axis=0).T)
acc = np.concatenate([[0], np.cumsum(seglen)])
L = acc[-1]
u = np.arange(0, L, STEP)
pts = np.stack([np.interp(u, acc, scr[:, 0]), np.interp(u, acc, scr[:, 1])], axis=1)

# entry: the front-most point of her silhouette around mid-frame
band = (pts[:, 1] > 540) & (pts[:, 1] < 660)
e = int(np.argmin(np.where(band, pts[:, 0], 1e9)))
A = pts[:e + 1][::-1]   # from E back to the path's start
B = pts[e:]             # from E on to the path's end
heart = [PHOTO["x"] + HEART_IMG[0] * PHOTO["s"], PHOTO["y"] + HEART_IMG[1] * PHOTO["s"]]
r = lambda P: [[round(float(x), 1), round(float(y), 1)] for x, y in P]
data = {"E": r(pts[e:e + 1])[0], "a": r(A), "b": r(B), "heart": heart}
with open(os.path.join(ROOT, "assets", "data", "silhouette.js"), "w", encoding="utf8") as f:
    f.write("// Generated by scripts/bake_silhouette.py — do not edit by hand.\n(function (g) { g.HERCOVA_SILHOUETTE = " + json.dumps(data) + "; })(typeof window !== 'undefined' ? window : globalThis);\n")
print(f"outline {L:.0f}px, E {data['E']}, pen A {len(A)} pts ({A[-1].round(0)}), pen B {len(B)} pts ({B[-1].round(0)}), heart {heart}")

# a proof sheet: the outline over the cut-out
proof = np.full((1080, 1920, 3), 255, np.uint8)
ph = cv2.resize(np.asarray(Image.open(os.path.join(ROOT, "assets", "images", "graded", "hero-subject.png")).convert("RGBA")), (800, 1000))
al = ph[..., 3:4].astype(np.float32) / 255
roi = proof[60:1060, 1040:1840].astype(np.float32)
proof[60:1060, 1040:1840] = (roi * (1 - al * 0.35) + ph[..., :3] * al * 0.35).astype(np.uint8)
cv2.polylines(proof, [np.round(A).astype(np.int32)], False, (168, 47, 123), 3, cv2.LINE_AA)
cv2.polylines(proof, [np.round(B).astype(np.int32)], False, (40, 120, 40), 3, cv2.LINE_AA)
cv2.circle(proof, tuple(int(v) for v in pts[e]), 9, (0, 0, 0), 2, cv2.LINE_AA)
cv2.circle(proof, tuple(int(v) for v in heart), 9, (30, 123, 238), -1, cv2.LINE_AA)
cv2.imwrite(os.path.join(ROOT, "snapshots", "silhouette-proof.jpg"), proof[:, 900:1920])
