// Bakes a dot-matrix map of Nigeria from the Natural Earth outline (public domain,
// via johan/world.geo.json) into assets/data/nigeria.js for the composition.
//
//   node scripts/build_map.mjs
//
// Output (all coordinates normalised to a 1000-unit-wide box, y down):
//   NIGERIA.outline  SVG path of the border
//   NIGERIA.dots     [[x, y, dist], ...] grid dots inside the border; dist = distance from HER
//   NIGERIA.her      [x, y] the one dot that is "her"
//   NIGERIA.lost     [x, y] the dot that dims at the 7-minute mark
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const geo = JSON.parse(fs.readFileSync(path.join(ROOT, 'assets/data/NGA.geo.json'), 'utf8'));
const ring = geo.features[0].geometry.coordinates[0];

const LAT0 = 9.1; // projection centre latitude
const k = Math.cos((LAT0 * Math.PI) / 180);
const proj = ([lon, lat]) => [lon * k, -lat];
const pts = ring.map(proj);
const minX = Math.min(...pts.map((p) => p[0]));
const maxX = Math.max(...pts.map((p) => p[0]));
const minY = Math.min(...pts.map((p) => p[1]));
const maxY = Math.max(...pts.map((p) => p[1]));
const S = 1000 / (maxX - minX);
const norm = ([x, y]) => [(x - minX) * S, (y - minY) * S];
const poly = pts.map(norm);
const H = (maxY - minY) * S;

function inside([x, y]) {
  let c = false;
  for (let i = 0, j = poly.length - 1; i < poly.length; j = i++) {
    const [xi, yi] = poly[i];
    const [xj, yj] = poly[j];
    if (yi > y !== yj > y && x < ((xj - xi) * (y - yi)) / (yj - yi) + xi) c = !c;
  }
  return c;
}

// Hex-offset grid reads more organic than a square one.
const STEP = 23;
const raw = [];
for (let row = 0, y = STEP / 2; y < H; row++, y += STEP * 0.866) {
  for (let x = (row % 2 ? STEP / 2 : 0) + STEP / 2; x < 1000; x += STEP) {
    if (inside([x, y])) raw.push([x, y]);
  }
}

// "Her": the grid dot nearest a rural point in the north-central belt (~8.7E, 10.6N).
const target = norm(proj([8.7, 10.6]));
const nearest = (t) => raw.reduce((b, p) => (Math.hypot(p[0] - t[0], p[1] - t[1]) < Math.hypot(b[0] - t[0], b[1] - t[1]) ? p : b));
const her = nearest(target);
// The dot that dims: far from her, in the south-west (~4.4E, 7.6N) — away from the eye's first read.
const lost = nearest(norm(proj([4.4, 7.6])));

const dots = raw.map(([x, y]) => [+x.toFixed(1), +y.toFixed(1), +Math.hypot(x - her[0], y - her[1]).toFixed(1)]);
const outline = 'M' + poly.map(([x, y]) => `${x.toFixed(1)} ${y.toFixed(1)}`).join('L') + 'Z';

const out = `// Generated by scripts/build_map.mjs — do not edit by hand.
(function (g) {
  g.NIGERIA = ${JSON.stringify({ w: 1000, h: +H.toFixed(1), outline, her: [her[0], her[1]], lost: [lost[0], lost[1]], dots })};
})(typeof window !== 'undefined' ? window : globalThis);
`;
fs.writeFileSync(path.join(ROOT, 'assets/data/nigeria.js'), out);
console.log(`dots ${dots.length}, box 1000 x ${H.toFixed(0)}, her ${her.map((v) => v.toFixed(0))}, lost ${lost.map((v) => v.toFixed(0))}`);
