// Exports Open Sauce One glyph outlines + kerning for 3D type (film/type3d.js builds per-letter extrusions).
//   node scripts/build_font3d.mjs            → assets/data/font3d.js  (window.HC_FONT3D[weight])
// Outlines use the facetype command letters Three's Font understands: m x y · l x y · q x y cx cy · b x y c1x c1y c2x c2y
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import opentype from 'opentype.js';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const WEIGHTS = [500, 700, 800];
const CHARSET = [...Array.from({ length: 95 }, (_, i) => String.fromCharCode(32 + i)), '’', '‘', '“', '”', '—', '–', '·', '→', '•', '…'];
const r = (v) => Math.round(v * 10) / 10;

const out = {};
for (const w of WEIGHTS) {
  const font = opentype.loadSync(path.join(ROOT, `assets/fonts/ttf/open-sauce-one-${w}.ttf`));
  const glyphs = {};
  const byChar = {};
  for (const ch of CHARSET) {
    const g = font.charToGlyph(ch);
    if (!g || (g.index === 0 && ch !== ' ')) continue;
    byChar[ch] = g;
    const cmds = g.getPath(0, 0, font.unitsPerEm).commands; // y down (screen space); flipped below
    let o = '';
    for (const c of cmds) {
      // opentype paths are y-down at size=unitsPerEm; facetype is y-up
      if (c.type === 'M') o += `m ${r(c.x)} ${r(-c.y)} `;
      else if (c.type === 'L') o += `l ${r(c.x)} ${r(-c.y)} `;
      else if (c.type === 'Q') o += `q ${r(c.x)} ${r(-c.y)} ${r(c.x1)} ${r(-c.y1)} `;
      else if (c.type === 'C') o += `b ${r(c.x)} ${r(-c.y)} ${r(c.x1)} ${r(-c.y1)} ${r(c.x2)} ${r(-c.y2)} `;
    }
    const bb = g.getBoundingBox();
    glyphs[ch] = { ha: g.advanceWidth, x_min: bb.x1, x_max: bb.x2, o: o.trim() };
  }
  // kerning for every pair in the charset that the font actually kerns
  const kern = {};
  const chars = Object.keys(byChar);
  for (const a of chars) for (const b of chars) {
    const k = font.getKerningValue(byChar[a], byChar[b]);
    if (k) kern[a + b] = k;
  }
  const os2 = font.tables.os2;
  out[w] = {
    unitsPerEm: font.unitsPerEm,
    ascender: font.ascender,
    descender: font.descender,
    capHeight: os2.sCapHeight || 700,
    xHeight: os2.sxHeight || 500,
    glyphs,
    kern,
  };
  console.log(w, Object.keys(glyphs).length, 'glyphs,', Object.keys(kern).length, 'kern pairs, cap', out[w].capHeight);
}
fs.writeFileSync(path.join(ROOT, 'assets/data/font3d.js'), `// Generated by scripts/build_font3d.mjs — Open Sauce One outlines + kerning for 3D type.\n(function (g) { g.HC_FONT3D = ${JSON.stringify(out)}; })(typeof window !== 'undefined' ? window : globalThis);\n`);
